title: The Xf4kt0r
description: My scratch pad for notes and things.
theme: jekyll-theme-hacker
production_url : https://xf4kt0r.github.io/
markdown: kramdown
has_children: true
plugins:
- jekyll-remote-theme